services:
  example-mysql:
    image: mysql:8.0-debian
    restart: always
    #    command: --lower_case_table_names=1
    container_name: example-mysql
    hostname: example-mysql
    ports:
      - "23306:3306"
    platform: linux/amd64
    environment:
      - MYSQL_USER=user
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=test1357
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1357
      - TZ=UTC
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - app_db:/var/lib/mysql
